name: "Second workflow"
on:
  push:
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Run echo command
          run: echo "2 nd pratice Workflow running"

        - name: Run standard checkout-actions
          uses: actions/checkout@v3
        
        - name: Run Upload artifact action
          uses: actions/upload-artifact@v3
        
        - name: Run echo command now for stating all actions sucessfully completed
          uses: echo "The upload and normal checkout actions have been completed sucessfully"
          


